### PR TITLE
Add button, icon, table, form, input, modal color components, modules and stories

### PR DESCRIPTION
**Pull request by suranyami**
@mcrumm I love this project idea, but it really looks like it could do with some extra hands to get it off the ground.

I'm planning on fleshing this out as part of a project I'm currently working on.

If you feel like adding me as a contributor, I'd be glad to run with it and see how much I can get completed. Alternatively, if not, I could push it up as a new library on hex.pm. Not sure what I'd call it though, since `bulma_components` pretty much says what it does on the tin.

Let me know what your preference is.

Currently working components:

## Buttons
```elixir
:color
:size
:light
:responsive
:outlined
:inverted
:rounded
:hovered
:focused
:active
:loading
:disabled
```

## Colors

```elixir
    :primary,
    :link,
    :info,
    :success,
    :warning,
    :danger
```

```elixir
    :white,
    :light,
    :dark,
    :black,
    :text,
    :ghost
```

## Icon

```elixir
:name
:class
:color
:size
:title
:fixed_width
:bordered
:spin
```

## Table

```elixir
:rows
:bordered
:striped
:narrow
:hoverable
:fullwidth
```

And stories for all of the above.

### CODE REVIEW

**Comment by mcrumm** [comment]
Hey @suranyami, thanks for the PR! I'd love to review this but as-is the vendored heroicons are making it almost impossible to load thru GitHub 🙃

Can you update this branch to override `:heroicons` in `mix.exs` and remove the vendor files as well? I pushed an example at 94165b5efc0e4aa137ac16afd2326f324f813b21, thanks!

**Comment by suranyami** [comment]
Will do! Did not realise that had happened. I guess that was part of the old storybook setup. They seemed to have changed something in Phoenix lately to pull down heroicons from Github. No idea why.

Sorry about that.

**Comment by suranyami** [comment]
* Fixed the `heroicons` issue as per your suggestion.
* Merged in the other work I had done on `Form`, `Input` and `Modal`.

**Comment by suranyami** [comment]
Replaced by #6

**Pull request closed without merging**
